name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Clojure CLI
      uses: DeLaGuardo/setup-clojure@13.1
      with:
        cli: latest
    - name: Cache deps
      uses: actions/cache@v4
      with:
        path: |
          .cpcache
          ~/.m2
          ~/.gitlibs
        key: ${{ runner.os }}-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Install deps
      run: |
        clojure -A:check:test:coverage -P
    - name: Run check
      run: clojure -M:check
    - name: Run tests
      run: clojure -M:test
    - name: Run tests for 1.11
      run: clojure -M:test:1.11
    - name: Run tests for 1.10
      run: clojure -M:test:1.10
    - name: Measure test coverage
      run: clojure -M:test:coverage
    - name: Upload coverage report to CodeCov
      uses: codecov/codecov-action@v5
